# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1183, 754)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("source/f(x).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.u_y_plot = u_y_plot(self.centralwidget)
        self.u_y_plot.setGeometry(QtCore.QRect(50, 20, 1021, 371))
        self.u_y_plot.setObjectName("u_y_plot")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 410, 881, 211))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("source/transfer function.png"))
        self.label.setObjectName("label")
        self.K_value = QtWidgets.QLineEdit(self.centralwidget)
        self.K_value.setGeometry(QtCore.QRect(460, 450, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.K_value.setFont(font)
        self.K_value.setObjectName("K_value")
        self.B_value = QtWidgets.QLineEdit(self.centralwidget)
        self.B_value.setGeometry(QtCore.QRect(670, 449, 113, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.B_value.setFont(font)
        self.B_value.setObjectName("B_value")
        self.A_value = QtWidgets.QLineEdit(self.centralwidget)
        self.A_value.setGeometry(QtCore.QRect(700, 490, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.A_value.setFont(font)
        self.A_value.setObjectName("A_value")
        self.M_value = QtWidgets.QLineEdit(self.centralwidget)
        self.M_value.setGeometry(QtCore.QRect(570, 550, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.M_value.setFont(font)
        self.M_value.setText("")
        self.M_value.setObjectName("M_value")
        self.rectangular = QtWidgets.QPushButton(self.centralwidget)
        self.rectangular.setGeometry(QtCore.QRect(120, 650, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rectangular.setFont(font)
        self.rectangular.setObjectName("rectangular")
        self.sine = QtWidgets.QPushButton(self.centralwidget)
        self.sine.setGeometry(QtCore.QRect(460, 650, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sine.setFont(font)
        self.sine.setObjectName("sine")
        self.step = QtWidgets.QPushButton(self.centralwidget)
        self.step.setGeometry(QtCore.QRect(800, 650, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.step.setFont(font)
        self.step.setObjectName("step")
        self.u_box = QtWidgets.QCheckBox(self.centralwidget)
        self.u_box.setGeometry(QtCore.QRect(1090, 170, 70, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.u_box.setFont(font)
        self.u_box.setChecked(True)
        self.u_box.setObjectName("u_box")
        self.y_box = QtWidgets.QCheckBox(self.centralwidget)
        self.y_box.setGeometry(QtCore.QRect(1090, 210, 70, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.y_box.setFont(font)
        self.y_box.setChecked(True)
        self.y_box.setObjectName("y_box")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1183, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Transfer function"))
        self.rectangular.setText(_translate("MainWindow", "rectangular function"))
        self.sine.setText(_translate("MainWindow", "sine wave"))
        self.step.setText(_translate("MainWindow", "step function"))
        self.u_box.setText(_translate("MainWindow", "u(t)"))
        self.y_box.setText(_translate("MainWindow", "y(t)"))
from u_y_plot import u_y_plot


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
